remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Geometry for Quantum Science
description: Official website of the GeQS project, supported by the Quantum Science and Nanomaterials Interdisciplinary Thematic Institute, University of Strasbourg
show_downloads: false

